---
title: Society of Work
timezone: America/New_York
collections:
  banners:
    title: Banners
    output: true
  members:
    title: Members
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    image: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: members
  values:
    first_name: 
    link: 
    link_text: 
    content: Nothing goes here
    image: 
    crazy_image: 
    position: 
    title: Replace with first and last name // for admin reference
    company: 
description: Society of Work is a shared coworking space in Chattanooga, TN with business
  flexibility in mind and resources to help like-minded people connect and create
  amazing things together.
baseurl: 
facebook: https://www.facebook.com/SocietyOfWork
twitter: https://twitter.com/SocietyofWork
instagram: http://instagram.com/societyofwork
linkedin: https://www.linkedin.com/company/society-of-work
tagline: Connect. Create. Cowork.
footer_news_letter_cta: Subscribe to our newsletter
footer_news_letter_description: Get the latest events and SoW news in your inbox.
logo: "/assets/img/logo/red-sow-logo.svg"
address: 1100 Market Street, Floor 6, Chattanooga, TN 37402
phone_number: 423-449-9112
url: https://www.societyofwork.com
cta_section:
  header: Ready to visit Society of Work?
  blue_button_txt: Find Tour Availability
  blue_button_link: https://calendly.com/societyofwork/tour?back=1
  white_button_txt: Book Conference Room
  white_button_link: https://external-bookings.apps.cobot.me/29b9a8f5-ca15-4713-8f25-33c58c18d3bd/book
  blue_aside_below_buttons: 'Special offer:'
  aside_below_buttons: free trial day pass with tour!
review_section:
  facebook_link_txt: Find more reviews on facebook
  facebook_link: https://www.facebook.com/pg/SocietyOfWork/reviews/
  reviews:
  - review: 
    testimonial: Society of Work is THE place to work and connect. I'm so grateful
      to have this place as source of focus + networking. There is no value I could
      place on how great this place has been for my work life/flow. And I love the
      feel of the coworking spaces, the vibe the building, and the amenities it provides!
    name: Kiersten Willams
  - review: 
    testimonial: Most importantly great tenants and hosts. The best place to plug
      into the startup community with great facilities and a constant flow of events
      that are enjoyable and topical.
    name: Tim Youngblood
  - review: 
    testimonial: We love working at Society of Work.  After having worked from home
      for some time, this space has been such a wonderful alternative to allow for
      more focused work and great interaction with others.  The community of people
      and the comfortable space is just right for our team. We couldn't be happier!
    name: Barbara Winchester
permalink: "/:title/"
markdown: kramdown
cloudinary:
  cloud_name: 
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 2000
      fallback_max_width: 1300
      steps: 5
      sizes: "(min-width: 1100px) 957px, 100vw"
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
- gulpfile.js
- _assets
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-cloudinary
